### ISSUE TITLE
NavigationPanelExtension v0.3.2 with Nette 2.4

### ISSUE THREAD

**Issue by JStika** [contributte/tracy#18]
Hi,

how to use NavigationPanelExtension v0.3.2 with Nette 2.4?

I got error with usage:
tracy.navigation:
      debug: %debugMode%

**Nette\InvalidStateException
Unknown configuration option 'tracy.navigation › debug'.** 

I got error without usage:
tracy.navigation:
      debug: %debugMode%

**Nette\InvalidStateException
Circular reference detected for services: tracy.bar, application.linkGenerator, routing.router, 114, security.user, security.userStorage, session.session.**

**Comment by f3l1x** [comment]
ping @mabar

**Comment by JStika** [comment]
No answer?

**Comment by f3l1x** [comment]
🤔

**Comment by JStika** [comment]
Why? No support?

**Comment by f3l1x** [comment]
Hey @JStika. It’s saturday. I pinged @mabar for more info. It’s maximum I can do for you at this moment.

**Comment by JStika** [comment]
It's pity.
Thx.

**Comment by mabar** [comment]
> Nette\InvalidStateException
 Unknown configuration option 'tracy.navigation › debug'.

There is no `debug` option in version 0.3.2, registered extension always adds panel to Tracy. It was added in 0.4.0

> Nette\InvalidStateException
Circular reference detected for services: tracy.bar, application.linkGenerator, routing.router, 114, security.user, security.userStorage, session.session.

Generally speaking - Nette don't know how to create services because they depend on each other. It can be workarounded with Nette\DI\Container requested as a service and a call `container->getService(...)` to get the service which causes circular reference. Only rule is getService() cannot be called in `__construct()` and `inject*()` methods

We may try use that workaround in our Tracy panel, but Nette 2.4 is not supported anymore and so are our libraries with Nette 2.4 support.

**Comment by JStika** [comment]
Can you send me example, I'm not Nette's expert.
Thx.

**Comment by mabar** [comment]
```php
class Example {

  /** @var \Nette\DI\Container **/
  private $container;

  public function __construct(\Nette\DI\Container $container)
  {
    $this->container = $container;
  }

  public function methodWhereIsServiceCausingCircularReferenceNeeded()
  {
    /** @var \Nette\Security\User $user **/
    $user = $container->getService('security.user');
    // or
    $user = $container->getServiceByType(\Nette\Security\User::class);
  }

}
```

**Comment by JStika** [comment]
Hm....

**Comment by f3l1x** [comment]
Feel free to open it with more questions. Also consider to support Contributte team (https://contributte.org/).
